In [1]:
import numpy as np

In [ ]:
np.

In [4]:
a1 = np.array([1, 2, 3])    
a2 = np.array([[1, 2], [3, 4]]) 
a3 = np.array([[[1, 2], [3, 4]],   
               [[5, 6], [7, 8]]])
print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
a0 = np.zeros((3, 3))
a1  = np.ones((2, 2))
ar  = np.arange(0, 10, 2)
print(a0)
print(a1)
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


In [6]:
a1 = np.array([10, 20, 30, 40, 50])
print(a1[2])     
print(a1[-1])     
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(a2[1, 0])   

30
50
4


In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a[1:2])     
print(a[:, 1])  

[[4 5 6]]
[2 5]


In [8]:
a = np.array([10, 20, 30, 40, 50, 60])
idx = np.array([1, 3, 5])
print(a[idx])      
cond = a > 30
print(a[cond])

[20 40 60]
[40 50 60]


In [9]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)   
print(x - y)    
print(x * y)  
print(x / y)    

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [10]:
a = np.array([-3, -1, 0, 1, 3])
print(np.absolute(a))

[3 1 0 1 3]


In [11]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
res = np.add(a1, a2)
print(res)

[5 7 9]


In [12]:
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))
b = np.array([0, 1, 2, 3])
print(np.exp(b))
print(np.sqrt(b))
print (np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[0.         1.25331414 1.77245385]


In [13]:
dtype = [('name', 'S10'), ('year', int), ('cgpa', float)]
vals  = [('Hrithik', 2009, 8.5),
         ('Ajay',    2008, 8.7),
         ('Pankaj',  2008, 7.9),
         ('Aakash',  2009, 9.0)]
a = np.array(vals, dtype=dtype)
print(np.sort(a, order='name'))
print(np.sort(a, order=['year', 'cgpa']))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
